### ISSUE TITLE
 Experimental Results

### ISSUE THREAD

**Issue by ForestNobear** [ddsediri/IterativePFN#1]
Thank you for your fascinating work! I would like to know whether the numerical results of the test data in the article, even at the maximum noise level, are all the results of a single iteration?
And I have the same problem with the other comparison methods.

**Comment by ddsediri** [comment]
Hi @ForestNobear, thank you for your interest in our work. All IterativePFN results are for a single run through the network comprising 4 ItMs. For the other methods, we have kept their testing settings intact when it comes to iteration number (we've used their original implementation since methods such as ScoreDenoise and PDFlow were trained on PUNet data by their authors).

**Comment by misszhou966** [comment]
Sorry to bother you, I want to train the model, but I have been experiencing the following error while running train.py. Could you please help me guide me. The error is RuntimeError: scatter-reduce_cuda does not have a deterministic implementation, but you set 'torch. use_deterministic-algorithms (True)' You can turn off determinism just for this operation, or you can use the 'warn only=True' option, if that's acceptable for your application You can also file an issue at https://github.com/pytorch/pytorch/issues To help us prioritize adding term inistic support for this operation
