### ISSUE TITLE
About Train

### ISSUE THREAD

**Issue by misszhou966** [ddsediri/IterativePFN#2]
Sorry to bother you, I want to train the model, but I have been experiencing the following error while running train.py. Could you please help me guide me. The error is RuntimeError: scatter-reduce_cuda does not have a deterministic implementation, but you set 'torch. use_deterministic-algorithms (True)' You can turn off determinism just for this operation, or you can use the 'warn only=True' option, if that's acceptable for your application You can also file an issue at https://github.com/pytorch/pytorch/issues To help us prioritize adding term inistic support for this operation

**Comment by ddsediri** [comment]
Hi @misszhou966, it might be due to a mismatch of the pytorch lightning (PL) version and also pytorch geometric (PyG) since PyG uses scatter for aggregation. The PL version we used was 1.7.6 and PyG was 2.0.4. You can check with this config if you still get the error. 

If not next step to troubleshoot would be to set deterministic=False at the following line: https://github.com/ddsediri/IterativePFN/blob/79efe407395b404d6d27550cfe64b2344cfe93c0/train.py#L49. The scatter functions are not deterministic in PyTorch, from what I know, and even setting it in PL doesn't enforce it.

**Comment by misszhou966** [comment]
Thank you very much for your prompt reply. As you said, I found my PyG was 2.3.1. When I downloaded it again, the error was resolved.

**Comment by ddsediri** [comment]
@misszhou966 good to hear!
